name: Bug report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Your issue may have already been reported. Please check the following link for common issues and solutions.

        [Commonly faced issues and their solutions](https://github.com/KillianLucas/open-interpreter/issues/164)
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: system
    attributes:
      label: System (please complete the following information).
      placeholder: |
        - OS: [e.g. iOS]
        - Python version [e.g. 3.10]
        - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] 
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
